apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fraud-detection-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/OWNER/mlops-fraud-pipeline.git
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: mlops-fraud
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
